# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: python-teamcity-messages.spec

# add or remove files that should be synced
synced_files:
    - python-teamcity-messages.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: teamcity-messages
# downstream (Fedora) RPM package name
downstream_package_name: teamcity-messages

upstream_project_url: https://github.com/majamassarini/teamcity-messages

upstream_tag_template: v{version}

jobs:
- job: copr_build
  trigger: commit
  metadata:
    targets: fedora-stable